-- TABELA DE PERFIS DE USUÁRIO (Estendendo o Auth do Supabase)
CREATE TYPE user_role AS ENUM ('ATHLETE', 'ADMIN', 'SUPPORT');

CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role user_role DEFAULT 'ATHLETE',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE TORNEIOS (Migrada do SQLite)
CREATE TABLE tournaments (
  id_tournament BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  location TEXT,
  entry_fee DECIMAL(10,2),
  rules_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE QUADRAS
CREATE TABLE courts (
  id_court BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  name TEXT NOT NULL,
  order_index INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE ATLETAS (Vinculada ao Auth se logado, ou apenas registro)
CREATE TABLE players (
  id_player BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id), -- Opcional para atletas que criarem conta
  name TEXT NOT NULL,
  matricula TEXT, -- Número de matrícula/ID
  data_nascimento DATE, -- Data de nascimento
  cpf TEXT, -- CPF (Brazilian ID)
  rg TEXT, -- RG (National ID)
  whatsapp TEXT,
  endereco TEXT, -- Full address
  numero TEXT, -- Address number
  complemento TEXT, -- Address complement
  cep TEXT, -- Postal code
  tamanho_camiseta TEXT CHECK (tamanho_camiseta IN ('P', 'M', 'G', 'GG')), -- T-shirt size
  atendido_por TEXT, -- Staff member who attended registration
  side TEXT CHECK (side IN ('RIGHT', 'LEFT', 'EITHER')),
  payment_status TEXT CHECK (payment_status IN ('PENDING', 'PAID', 'CANCELLED')) DEFAULT 'PENDING',
  stripe_session_id TEXT,
  has_lunch BOOLEAN DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE DUPLAS
CREATE TABLE doubles (
  id_double BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  id_player1 BIGINT REFERENCES players(id_player),
  id_player2 BIGINT REFERENCES players(id_player),
  display_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE GRUPOS
CREATE TABLE groups (
  id_group BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RELAÇÃO GRUPOS x DUPLAS
CREATE TABLE groups_doubles (
  id_group_double BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_group BIGINT REFERENCES groups(id_group) ON DELETE CASCADE,
  id_double BIGINT REFERENCES doubles(id_double) ON DELETE CASCADE,
  points INT DEFAULT 0,
  matches_played INT DEFAULT 0
);

-- TABELA DE JOGOS
CREATE TABLE matches (
  id_match BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  id_group BIGINT REFERENCES groups(id_group),
  stage TEXT DEFAULT 'GROUP',
  id_double_a BIGINT REFERENCES doubles(id_double),
  id_double_b BIGINT REFERENCES doubles(id_double),
  id_court BIGINT REFERENCES courts(id_court),
  scheduled_at TIMESTAMP WITH TIME ZONE,
  planned_duration_min INT DEFAULT 30,
  games_double_a INT DEFAULT 0,
  games_double_b INT DEFAULT 0,
  status TEXT CHECK (status IN ('TO_PLAY', 'CALLING', 'IN_PROGRESS', 'FINISHED')) DEFAULT 'TO_PLAY',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS (Row Level Security) - Permitir leitura pública, escrita apenas autenticada
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public tournaments are viewable by everyone" ON tournaments FOR SELECT USING (true);

-- TABELA DE CATEGORIAS (Master, A, B, etc)
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  active INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE FASES DO TORNEIO (2026-02, 2026-03, etc)
CREATE TABLE tournament_phases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  phase_name TEXT,
  status TEXT CHECK (status IN ('REGISTRATION', 'CLOSED', 'drawn', 'SCHEDULED', 'IN_PROGRESS', 'FINISHED')) DEFAULT 'REGISTRATION',
  registration_deadline TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ADICIONA colunas category_id e is_socio à tabela players (Ranking SRB)
ALTER TABLE players ADD COLUMN category_id BIGINT REFERENCES categories(id);
ALTER TABLE players ADD COLUMN is_socio BOOLEAN DEFAULT TRUE;

-- TABELA DE DUPLAS JÁ SORTEADAS (evitar repetição)
CREATE TABLE drawn_doubles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_id BIGINT REFERENCES tournament_phases(id) ON DELETE CASCADE,
  athlete1_id BIGINT REFERENCES players(id_player) ON DELETE CASCADE,
  athlete2_id BIGINT REFERENCES players(id_player) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(phase_id, athlete1_id, athlete2_id)
);

-- ADICIONA colunas de moderação à tabela matches
ALTER TABLE matches ADD COLUMN moderator_approved INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN moderator_notes TEXT;
ALTER TABLE matches ADD COLUMN submitted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE matches ADD COLUMN result_submitter_id UUID REFERENCES auth.users(id);

-- TABELA DE RODADAS (Ranking SRB - rounds com duplas por rodada)
CREATE TABLE rounds (
  id_round BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  id_category BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  round_number INT NOT NULL,
  scheduled_date DATE NOT NULL,
  window_start TIME DEFAULT '18:00',
  window_end TIME DEFAULT '23:00',
  makeup_deadline DATE,
  notes TEXT,
  status TEXT CHECK (status IN ('PENDING', 'IN_PROGRESS', 'FINISHED')) DEFAULT 'PENDING',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(id_tournament, id_category, round_number)
);

-- Adiciona coluna id_round à tabela doubles (para rastreio de rodada)
ALTER TABLE doubles ADD COLUMN id_round BIGINT REFERENCES rounds(id_round) ON DELETE CASCADE;

-- Trigger para criar perfil automaticamente ao registrar no Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'ATHLETE');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
