-- TABELA DE PERFIS DE USUÁRIO (Estendendo o Auth do Supabase)
CREATE TYPE user_role AS ENUM ('ATHLETE', 'ADMIN', 'SUPPORT');

CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role user_role DEFAULT 'ATHLETE',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE TORNEIOS (Migrada do SQLite)
CREATE TABLE tournaments (
  id_tournament BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  location TEXT,
  entry_fee DECIMAL(10,2),
  rules_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE QUADRAS
CREATE TABLE courts (
  id_court BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  name TEXT NOT NULL,
  order_index INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE ATLETAS (Vinculada ao Auth se logado, ou apenas registro)
CREATE TABLE players (
  id_player BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id), -- Opcional para atletas que criarem conta
  name TEXT NOT NULL,
  whatsapp TEXT,
  side TEXT CHECK (side IN ('RIGHT', 'LEFT', 'EITHER')),
  payment_status TEXT CHECK (payment_status IN ('PENDING', 'PAID', 'CANCELLED')) DEFAULT 'PENDING',
  stripe_session_id TEXT,
  has_lunch BOOLEAN DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE DUPLAS
CREATE TABLE doubles (
  id_double BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  id_player1 BIGINT REFERENCES players(id_player),
  id_player2 BIGINT REFERENCES players(id_player),
  display_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABELA DE GRUPOS
CREATE TABLE groups (
  id_group BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RELAÇÃO GRUPOS x DUPLAS
CREATE TABLE groups_doubles (
  id_group_double BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_group BIGINT REFERENCES groups(id_group) ON DELETE CASCADE,
  id_double BIGINT REFERENCES doubles(id_double) ON DELETE CASCADE,
  points INT DEFAULT 0,
  matches_played INT DEFAULT 0
);

-- TABELA DE JOGOS
CREATE TABLE matches (
  id_match BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tournament BIGINT REFERENCES tournaments(id_tournament) ON DELETE CASCADE,
  id_group BIGINT REFERENCES groups(id_group),
  stage TEXT DEFAULT 'GROUP',
  id_double_a BIGINT REFERENCES doubles(id_double),
  id_double_b BIGINT REFERENCES doubles(id_double),
  id_court BIGINT REFERENCES courts(id_court),
  scheduled_at TIMESTAMP WITH TIME ZONE,
  planned_duration_min INT DEFAULT 30,
  games_double_a INT DEFAULT 0,
  games_double_b INT DEFAULT 0,
  status TEXT CHECK (status IN ('TO_PLAY', 'CALLING', 'IN_PROGRESS', 'FINISHED')) DEFAULT 'TO_PLAY',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS (Row Level Security) - Permitir leitura pública, escrita apenas autenticada
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public tournaments are viewable by everyone" ON tournaments FOR SELECT USING (true);

-- Trigger para criar perfil automaticamente ao registrar no Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'ATHLETE');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
